threshold_warning: 20 # % of battery level
threshold_error: 10 # % of battery level
threshold_critical: 5 # % of battery level

enable_light: true
num_leds: 1
light_components: ['light']

enable_sound: false
